env:
  browser: true
  es2021: true
extends:
  - '@nuxtjs/eslint-config-typescript'
  - plugin:@typescript-eslint/recommended
  # - eslint:recommended
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - vue
rules:
  semi: ['error', 'always']
  comma-dangle: ['error', 'always-multiline']